- 异常捕获时，先捕获小异常，再捕获大异常
- 多异常捕获
    - 捕获多种异常时，多种异常类型之间用 ‘|’ 隔开
    - 捕获多种异常时，异常变量有隐式的final修饰

- 访问异常信息
    - getMessage()
    - printStackTrace()
    - printStackTrace(PrintStream s)
    - getStackTrace()

- try后面紧跟一对圆括号，可以声明，初始化一个或多个资源，try在该语句结束时自动关闭这些资源，节省了原来在finally中关闭资源的做法。
- 但这些资源必须实现AutoCloseable接口或者Closeable接口，实现其中的close()方法。
    - AutoCloseable的close()，声明抛出IOException
    - Closeable的close()，声明抛出Exception
- Java7几乎所有的资源类都实现了这两个接口中的一个

- finally 不会被执行的情况
    - try语句没有被执行到，如在try语句之前就返回了，这样finally语句就不会执行，这也说明了finally语句被执行的必要而非充分条件是：相应的try语句一定被执行到。
    - 在try块中有System.exit(0);这样的语句，System.exit(0);是终止Java虚拟机JVM的，连JVM都停止了，所有都结束了，当然finally语句也不会被执行到。

- checked exception 要求被显式的捕获或者抛出；抛出异常时，方法签名和异常耦合，子类重写父类方法，抛出的异常还要受被重写方法抛出异常的限制。
- 因此大部分时候，推荐使用runtime exception，无需在方法声明中抛出，只管直接抛出Runtime Exception异常；如果需要捕获，一样可以使用try...catch。
- checked exception优势：能在编译时提醒程序员可能存在的问题

- catch 和 throw同时使用
    - 在企业级应用中常用，因为企业级应用对异常的处理通常分为
        - 应用后台需要通过日志来记录异常发生的详细情况
        - 应用还需要根据异常向应用使用者传达某种提示

- 异常链
    - 对于企业级应用，有严格的分级关系，上层功能严格依赖下层的API，但不会跨层访问。因此，在持久层-业务逻辑层-表现层的分层结构时，不应该把持久层的异常传到用户界面。
    - 通常做法：程序先捕获原始异常，然后抛出一个新的业务异常，这种方式通常叫异常转译。

- [详解return和finally](http://www.cnblogs.com/lanxuezaipiao/p/3440471.html)
- 如果finally语句中没有return语句覆盖返回值，那么原来的返回值可能因为finally里的修改而改变也可能不变。

- 没有影响的案例
public class FinallyTest3 {

    public static void main(String[] args) {

        System.out.println(test3());
    }

    public static int test3() {
        int b = 20;

        try {
            System.out.println("try block");

            return b += 80;
        } catch (Exception e) {

            System.out.println("catch block");
        } finally {

            System.out.println("finally block");

            if (b > 25) {
                System.out.println("b>25, b = " + b);
            }

            b = 150;
        }

        return 2000;
    }

}
运行结果是：

try block
finally block
b>25, b = 100
100

- 有影响的案例
public class FinallyTest6
{
    public static void main(String[] args) {
        System.out.println(getMap().get("KEY").toString());
    }
     
    public static Map<String, String> getMap() {
        Map<String, String> map = new HashMap<String, String>();
        map.put("KEY", "INIT");
         
        try {
            map.put("KEY", "TRY");
            return map;
        }
        catch (Exception e) {
            map.put("KEY", "CATCH");
        }
        finally {
            map.put("KEY", "FINALLY");
            map = null;
        }
         
        return map;
    }
}
运行结果是：

FINALLY

简单来说就是：Java中只有传值没有传址，这也是为什么map = null这句不起作用，但map中的值被改变了，因为map是对象，return的map的地址不能被改变，其中的值是可以被改变。
而b的值没有在finally中发生改变，因为b是基础类型。
具体可以参考CrazyJava.edu.demon.exception10.ReturnFinallyDemo.java